### ISSUE TITLE
要是按原论文的数据集，该咋弄咧

### ISSUE THREAD

**Issue by Bhongcheng** [smduan/FedMix#1]

**Comment by smduan** [comment]
1、修改conf.py文件：
data_type:image
model_name :  simple-cnn
which_datasets : your_dataset

2、把图像数据按照图片格式存储，用个csv文件保存文件名和标签。格式如下：
data_column,label_column
./0.png,1

具体逻辑在main.py，主要注意数据格式，其他都已经实现了。

**Comment by Bhongcheng** [comment]
谢谢！
